version: '3.12.3'

services:
  # Selenium browser (Chrome)
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"    # Selenium WebDriver port
    shm_size: 2gb      # Fix for Chrome crashes in Docker
    networks:
      - selenium-net

  # Your Python script container
  script:
    build: .           # Uses your local Dockerfile
    depends_on:
      - selenium-chrome
    environment:
      SELENIUM_HUB: "http://selenium-chrome:4444"  # Connect via service name
    networks:
      - selenium-net
    env_file: 
      - .env           # Correct YAML list syntax

networks:
  selenium-net:        # Isolated network for communication