version: '3.12'

services:
  scraper:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file: ".env"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    # Uncomment if you need to debug with a visible browser
    # environment:
    #   - DISPLAY=:99
    # ports:
    #   - 5900:5900  # For VNC if you want to view the browser
