[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "logging>=0.4.9.6",
    "lxml-html-clean>=0.4.2",
    "pytubefix>=8.12.3",
    "requests-html>=0.10.0",
]
