[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "assemblyai>=0.9.0",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "pyppeteer>=2.0.0",
    "yt-dlp>=2025.3.31",
]
